language: ruby

rvm:
  - 1.9.3
  - ruby-head
  - jruby-19mode
  - rbx-2.2.9

before_install:
  - echo "Installing puppet"
  - sudo apt-get install unzip -q -yy
  - sudo apt-get install puppet -q -yy
  - echo "Running puppet"
  - sudo puppet apply --modulepath="puppet/modules" puppet/manifests/core.pp
  - echo "Updating rubygems"
  - gem update --system
  - echo "Updating bundler"
  - gem update bundler
  - # echo "Installing packer.io"
  - # mkdir packer
  - # cd packer
  - # wget https://dl.bintray.com/mitchellh/packer/0.6.0_linux_386.zip
  - # sudo unzip 0.6.0_linux_386.zip
  - # export PATH=$PATH:`pwd`
  - # packer -v
  - # cd ..
  
script: rake ci
