language: ruby

rvm:
  - 1.9.3
  - ruby-head
  - jruby-19mode
  - rbx-2.2.9

before_install:
  - gem update --system
  - gem update bundler
  - sudo apt-get install unzip
  - wget https://dl.bintray.com/mitchellh/packer/0.3.6_linux_386.zip
  - sudo unzip 0.3.6_linux_386.zip

script: rake ci
