language: ruby

sudo: false

cache: bundler

rvm:
  - 1.9.3
  - 2.1
  - 2.2
  - ruby-head
  - jruby-19mode

env:
  - TRAVIS_BUILD=true

before_install:
  - echo "Updating rubygems"
  - gem update --system
  - echo "Updating bundler"
  - gem update bundler

script: rake ci