#cloud-config

# See https://coreos.com/docs/cluster-management/setup/cluster-architectures/#configuration-for-worker-role10

coreos:
  fleet:
    etcd_servers: "http://10.133.206.19:4001" # Specify private IP of your etcd core os node
    metadata: role=kubernetes,public_ip=$public_ipv4,private_ip=$private_ipv4

  units:
    - name: etcd.service
     mask: true
    - name: fleet.service
     command: start
    - name: flannel.service
     command: start
     content: |
       [Unit]
       After=network-online.target
       Wants=network-online.target
       Description=flannel is an etcd backed overlay network for containers

       [Service]
       Type=notify
       ExecStartPre=-/usr/bin/mkdir -p /opt/bin
       ExecStartPre=/usr/bin/wget -N -P /opt/bin http://storage.googleapis.com/flannel/flanneld
       ExecStartPre=/usr/bin/chmod +x /opt/bin/flanneld
       ExecStart=/opt/bin/flanneld -etcd-endpoint http://10.133.206.19:4001
    - name: docker.service
     command: start
     content: |
       [Unit]
       After=flannel.service
       Wants=flannel.service
       Description=Docker Application Container Engine
       Documentation=http://docs.docker.io

       [Service]
       EnvironmentFile=/run/flannel/subnet.env
       ExecStartPre=/bin/mount --make-rprivate /
       ExecStart=/usr/bin/docker -d --bip=${FLANNEL_SUBNET} --mtu=${FLANNEL_MTU} -s=btrfs -H fd://

       [Install]
       WantedBy=multi-user.target
    - name: setup-network-environment.service
     command: start
     content: |
       [Unit]
       Description=Setup Network Environment
       Documentation=https://github.com/kelseyhightower/setup-network-environment
       Requires=network-online.target
       After=network-online.target

       [Service]
       ExecStartPre=-/usr/bin/mkdir -p /opt/bin
       ExecStartPre=/usr/bin/wget -N -P /opt/bin http://storage.googleapis.com/snenv/setup-network-environment
       ExecStartPre=/usr/bin/chmod +x /opt/bin/setup-network-environment
       ExecStart=/opt/bin/setup-network-environment
       RemainAfterExit=yes
       Type=oneshot
  update:
    group: stable
    reboot-strategy: off

write_files:
  - path: /etc/profile.d/etcdctl.sh
    permissions: 0644
    owner: core
    content: |
      # configure etcdctl to work with our etcd servers set above
      export ETCDCTL_PEERS="http://10.133.206.19:4001" # Specify private IP of your etcd core os node
  - path: /etc/profile.d/fleetctl.sh
    permissions: 0644
    owner: core
    content: |
      # configure fleetctl to work with our etcd servers set above
      export FLEETCTL_ENDPOINT=/var/run/fleet.sock
      export FLEETCTL_EXPERIMENTAL_API=true