#cloud-config

# See https://coreos.com/docs/cluster-management/setup/cluster-architectures/#configuration-for-worker-role10

coreos:
  fleet:
    etcd_servers: "http://10.133.206.19:4001" # Specify private IP of your etcd core os node
    metadata: role=kubernetes,public_ip=$public_ipv4,private_ip=$private_ipv4

  units:
    - name: etcd.service
      mask: true
    - name: fleet.service
      command: start
    - name: docker.service
      command: start
  update:
    group: stable
    reboot-strategy: off
write_files:
  - path: /etc/profile.d/etcdctl.sh
    permissions: 0644
    owner: core
    content: |
      # configure etcdctl to work with our etcd servers set above
      export ETCDCTL_PEERS="http://10.133.206.19:4001" # Specify private IP of your etcd core os node
  - path: /etc/profile.d/fleetctl.sh
    permissions: 0644
    owner: core
    content: |
      # configure fleetctl to work with our etcd servers set above
      export FLEETCTL_ENDPOINT=/var/run/fleet.sock
      export FLEETCTL_EXPERIMENTAL_API=true